models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Musica(db.Model):
    __tablename__ = 'music'
    id = db.Column(db.Integer, primary_key=True)
    titulo = db.Column(db.String(80), nullable=False)
    artista = db.Column(db.String(80), nullable=False)
    video = db.Column(db.String(800), nullable=False)
    link = db.Column(db.String(800), nullable=False)
    genero = db.Column(db.String(80))

    def __repr__(self):
        return f'<Musica {self.titulo}>'

app.py
from flask import Flask, render_template, request, redirect, url_for
from flask_migrate import Migrate
from models import db, Musica
from controllers.musica import musica_bp

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://teste:teste@localhost/music'

db.init_app(app)

migrate = Migrate(app, db)

app.register_blueprint(musica_bp)

@app.route('/')
def index():
    musicas = Musica.query.all()
    if not musicas:
        return render_template('index.html', mensagem='Nenhuma música cadastrada')
    else:
        return render_template('index.html', musicas=musicas)

@app.route('/cadastro')
def cadastro():
    return render_template('cadastro.html')

@app.route('/deletar')
def deletar():
    musicas = Musica.query.all()
    if not musicas:
        return render_template('deletar.html', mensagem='Nenhuma música cadastrada')
    else:
        return render_template('deletar.html', musicas=musicas)
    #return render_template('deletar.html')

controllers/musica.py
from flask import Blueprint, request, jsonify, render_template, redirect, url_for, current_app
from models import db, Musica
from flask import flash

musica_bp = Blueprint('musica_bp', __name__)

# Renderizar o formulário de cadastro de música
@musica_bp.route('/musicas/cadastrar', methods=['GET'])
def form_cadastro_musica():
    return render_template('cadastro_musica.html')

@musica_bp.route('/musicas', methods=['POST'])
def create_musica():
    titulo = request.form['titulo']
    artista = request.form['artista']
    video = request.form['video']
    link = request.form['link']
    genero = request.form.get('genero', None)

    musica = Musica(titulo=titulo, artista=artista, video=video, link=link, genero=genero)

    db.session.add(musica)
    db.session.commit()

    #return render_template('cadastro.html')
    return render_template('cadastro.html', comunicacao=f'Música {titulo}, criada com sucesso!')



# Renderizar o formulário de excluir de música
@musica_bp.route('/deletar/deletar', methods=['GET'])
def form_delete_musica():
    return render_template('deletar_musica.html')

# Deletar uma músicas por ID
@musica_bp.route('/deletar', methods=['POST'])
def delete_musica():
    ids = request.form.getlist('musica_ids[]')

    print(f'IDs: {ids}')

    if not ids:
        musicas = Musica.query.all()
        return render_template('deletar.html', musicas=musicas, comunicacao='Nenhuma música selecionada para exclusão')
    for id in ids:
        musica = Musica.query.get(id)
        if not musica:
            return render_template('deletar.html', comunicacao=f'Música não encontrada!')
        titulo = musica.titulo
        db.session.delete(musica)
    db.session.commit()

    musicas = Musica.query.all()

    if not musicas:
        return render_template('deletar.html', mensagem='Nenhuma música cadastrada')
    else:
        return render_template('index.html', musicas=musicas, comunicacao=f'Música {titulo}, excluida com sucesso!')



# Obter todas as músicas
@musica_bp.route('/musicas', methods=['GET'])
def get_musicas():
    musicas = Musica.query.all()
    return render_template('index.html', musicas=musicas)

# Obter uma música específica por ID
@musica_bp.route('/musicas/<int:musica_id>', methods=['GET'])
def get_musica(musica_id):
    musica = Musica.query.get(musica_id)

    if not musica:
        return jsonify({'message': 'Musica não encontrada'}), 404

    return jsonify(musica.__dict__)

# Atualizar uma música específica por ID
@musica_bp.route('/musicas/<int:musica_id>', methods=['POST', 'PUT'])
def update_musica(musica_id):
    musica = Musica.query.get(musica_id)

    if not musica:
        return jsonify({'message': 'Musica não encontrada'}), 404

    musica.titulo = request.form['titulo']
    musica.artista = request.form['artista']
    musica.video = request.form['video']
    musica.link = request.form['link']
    musica.genero = request.form.get('genero', None)

    db.session.commit()

    flash('Música atualizada com sucesso!')

    return redirect(url_for('musica_bp.get_musicas'))

"""# Deletar uma música específica por ID
@musica_bp.route('/musicas', methods=['POST'])
def delete_musica(musica_id):
    musica = Musica.query.get(musica_id)

    if not musica:
        return jsonify({'message': 'Musica não encontrada'}), 404

    db.session.delete(musica)
    db.session.commit()

    flash('Música deletada com sucesso!')

    return render_template('deletar.html', musica_deletada=True)"""

templates/cadastro.html
{% extends "main.html" %}

{% block content %}

  <h1 class="text-center">Cadastrar nova música</h1>

  <div class="separador"></div><br>

  <form method="POST" action="{{ url_for('musica_bp.create_musica') }}">

    <div>
      <label for="titulo">Título:</label>
      <input type="text" name="titulo" id="titulo" required>
    </div><br>

    <div>
      <label for="artista">Artista:</label>
      <input type="text" name="artista" id="artista" required>
    </div><br>

    <div>
      <label for="video">Vídeo:</label>
      <input type="text" name="video" id="video" required>
    </div><br>

    <div>
      <label for="link">Link:</label>
      <input type="text" name="link" id="link" required>
    </div><br>

    <div>
      <label for="genero">Gênero:</label>
      <input type="text" name="genero" id="genero">
    </div><br>

    <div class="text-center">
      <button type="submit">Cadastrar</button>
    </div><br>

  </form>

{% endblock %}

templates/deletar.html
{% extends "main.html" %}

{% block content %}

  {% if mensagem %}
    <h2 class="text-center">{{ mensagem }}</h2>

    {% else %}

    <h1 class="text-center">Excluir música</h1>

    <form method="POST" action="{{ url_for('musica_bp.delete_musica') }}">

        {% for musica in musicas %}

            <div class="separador"></div><br>

            <div class="organizador">

                <input type="checkbox" id="{{ musica.id }}" value="{{ musica.id }}" name="musica_ids[]">

                <div class="video mx-2">{{ musica.video | safe }}</div>

                <div class="texto">

                    <h4>Título: {{ musica.titulo }}</h4>
                    <p>Artista: {{ musica.artista }}</p>
                    <p>Gênero: {{ musica.genero }}</p>
                    <p>Link: <a href="{{ musica.link }}" target="_blank">{{ musica.link }}</a></p>

                </div>

            </div>

            <br>

        {% endfor %}

        <div class="separador"></div><br>

        <div class="text-center">
            <button type="submit" class="btn btn-danger mx-auto">Deletar</button>
        </div><br>

        <div class="separador"></div>

    </form>

  {% endif %}

{% endblock %}

templates/index.html
{% extends "main.html" %}

{% block content %}

        {% if mensagem %}
            <h2 class="text-center">{{ mensagem }}</h2>

            {% else %}

                <h2 class="text-center">Minhas Músicas</h2>

                {% for musica in musicas %}

                    <div class="separador"></div><br>

                    <div class="organizador">

                        <div class="video mx-2">{{ musica.video | safe }}</div>

                        <div class="texto">

                            <h4>Título: {{ musica.titulo }}</h4>
                            <p>Artista: {{ musica.artista }}</p>
                            <p>Gênero: {{ musica.genero }}</p>
                            <p>Link: <a href="{{ musica.link }}" target="_blank">{{ musica.link }}</a></p>

                        </div>

                    </div>

                    <br>

            {% endfor %}

        {% endif %}

{% endblock %}

templates/main.html
<!DOCTYPE html>

<html lang="pt-BR">

  <head>

    <link rel="icon" href="{{ url_for('static', filename='images/logo.png') }}" type="image/x-icon">
    <title>Musics</title>

    <meta charset="utf-8">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/BootStrap/bootstrap.min.css') }}">

  </head>

  <body>

    <script>

      {% if comunicacao %}
        alert("{{ comunicacao }}");
      {% endif %}

    </script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <a style="margin-left: 250px" class="navbar-brand" href="/">
        <img src="{{ url_for('static', filename='images/logo.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
        Musics
      </a>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">Minhas Músicas</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('cadastro') }}">Cadastrar Música</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('deletar') }}">Excluir Música</a>
          </li>

        </ul>
      </div>

    </nav>

    <br>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <br>

    <!-- coloque aqui o código do rodapé da página -->

  </body>

  <footer class="bg-dark text-center text-white mt-5">
    <p>&copy; 2023 Musics</p>
  </footer>

</html>